# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Programming\Project\Python\gey2008\UI\MainWnd.ui'
#
# Created: Sat Oct 04 11:34:50 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(574, 505)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        mainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menuView = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuView.setFont(font)
        self.menuView.setObjectName("menuView")
        self.menuFuzzy_GIS_Modeling = QtGui.QMenu(self.menubar)
        self.menuFuzzy_GIS_Modeling.setObjectName("menuFuzzy_GIS_Modeling")
        self.menuCriteria_Weight_Dertermine = QtGui.QMenu(self.menubar)
        self.menuCriteria_Weight_Dertermine.setObjectName("menuCriteria_Weight_Dertermine")
        self.menuNEG_Simulation = QtGui.QMenu(self.menubar)
        self.menuNEG_Simulation.setObjectName("menuNEG_Simulation")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAHP = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionAHP.setFont(font)
        self.actionAHP.setObjectName("actionAHP")
        self.actionLingTbl = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionLingTbl.setFont(font)
        self.actionLingTbl.setObjectName("actionLingTbl")
        self.actionLocGen = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionLocGen.setFont(font)
        self.actionLocGen.setObjectName("actionLocGen")
        self.actionSave = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionSaveAs.setFont(font)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClearExistFeatcls = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionClearExistFeatcls.setFont(font)
        self.actionClearExistFeatcls.setObjectName("actionClearExistFeatcls")
        self.actionNew = QtGui.QAction(mainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionDistMatGen = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionDistMatGen.setFont(font)
        self.actionDistMatGen.setObjectName("actionDistMatGen")
        self.actionProxAnalyst = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionProxAnalyst.setFont(font)
        self.actionProxAnalyst.setObjectName("actionProxAnalyst")
        self.actionImport = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionImport.setFont(font)
        self.actionImport.setObjectName("actionImport")
        self.actionSensViewer = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionSensViewer.setFont(font)
        self.actionSensViewer.setObjectName("actionSensViewer")
        self.actionClipFilter = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionClipFilter.setFont(font)
        self.actionClipFilter.setObjectName("actionClipFilter")
        self.actionShowAltRank = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionShowAltRank.setFont(font)
        self.actionShowAltRank.setObjectName("actionShowAltRank")
        self.actionShowAbsChg = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionShowAbsChg.setFont(font)
        self.actionShowAbsChg.setObjectName("actionShowAbsChg")
        self.actionShowRelChg = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionShowRelChg.setFont(font)
        self.actionShowRelChg.setObjectName("actionShowRelChg")
        self.actionShowSensList = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.actionShowSensList.setFont(font)
        self.actionShowSensList.setObjectName("actionShowSensList")
        self.actionShowThVal = QtGui.QAction(mainWindow)
        self.actionShowThVal.setObjectName("actionShowThVal")
        self.actionShowCrtDegs = QtGui.QAction(mainWindow)
        self.actionShowCrtDegs.setObjectName("actionShowCrtDegs")
        self.actionShowSens = QtGui.QAction(mainWindow)
        self.actionShowSens.setObjectName("actionShowSens")
        self.actionConCrtTrees = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionConCrtTrees.setFont(font)
        self.actionConCrtTrees.setObjectName("actionConCrtTrees")
        self.actionSetLingVal = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionSetLingVal.setFont(font)
        self.actionSetLingVal.setObjectName("actionSetLingVal")
        self.actionBldRegPg = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionBldRegPg.setFont(font)
        self.actionBldRegPg.setObjectName("actionBldRegPg")
        self.actionCompCrtProx = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionCompCrtProx.setFont(font)
        self.actionCompCrtProx.setObjectName("actionCompCrtProx")
        self.actionAHPMatCon = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionAHPMatCon.setFont(font)
        self.actionAHPMatCon.setObjectName("actionAHPMatCon")
        self.actionSensAnalyst = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionSensAnalyst.setFont(font)
        self.actionSensAnalyst.setObjectName("actionSensAnalyst")
        self.actionRandom_Matrix = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionRandom_Matrix.setFont(font)
        self.actionRandom_Matrix.setObjectName("actionRandom_Matrix")
        self.actionAutoExp = QtGui.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionAutoExp.setFont(font)
        self.actionAutoExp.setObjectName("actionAutoExp")
        self.actionWPMSensAnalyst = QtGui.QAction(mainWindow)
        self.actionWPMSensAnalyst.setObjectName("actionWPMSensAnalyst")
        self.actionTreeRenderer = QtGui.QAction(mainWindow)
        self.actionTreeRenderer.setObjectName("actionTreeRenderer")
        self.actionGenDistMat = QtGui.QAction(mainWindow)
        self.actionGenDistMat.setObjectName("actionGenDistMat")
        self.actionSimulation = QtGui.QAction(mainWindow)
        self.actionSimulation.setObjectName("actionSimulation")
        self.menu.addAction(self.actionNew)
        self.menu.addSeparator()
        self.menu.addAction(self.actionOpen)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveAs)
        self.menuView.addAction(self.actionImport)
        self.menuView.addAction(self.actionTreeRenderer)
        self.menuView.addAction(self.actionAutoExp)
        self.menuFuzzy_GIS_Modeling.addAction(self.actionSetLingVal)
        self.menuFuzzy_GIS_Modeling.addAction(self.actionConCrtTrees)
        self.menuFuzzy_GIS_Modeling.addAction(self.actionBldRegPg)
        self.menuFuzzy_GIS_Modeling.addAction(self.actionCompCrtProx)
        self.menuCriteria_Weight_Dertermine.addAction(self.actionAHPMatCon)
        self.menuCriteria_Weight_Dertermine.addAction(self.actionRandom_Matrix)
        self.menuCriteria_Weight_Dertermine.addAction(self.actionSensAnalyst)
        self.menuCriteria_Weight_Dertermine.addAction(self.actionWPMSensAnalyst)
        self.menuNEG_Simulation.addAction(self.actionGenDistMat)
        self.menuNEG_Simulation.addAction(self.actionSimulation)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuFuzzy_GIS_Modeling.menuAction())
        self.menubar.addAction(self.menuCriteria_Weight_Dertermine.menuAction())
        self.menubar.addAction(self.menuNEG_Simulation.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Geographical Factor Evaluator", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("mainWindow", "File(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("mainWindow", "Tools(&T)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFuzzy_GIS_Modeling.setTitle(QtGui.QApplication.translate("mainWindow", "Fuzzy GIS Modeling(&M)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCriteria_Weight_Dertermine.setTitle(QtGui.QApplication.translate("mainWindow", "Criterion(&C)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNEG_Simulation.setTitle(QtGui.QApplication.translate("mainWindow", "NEG Simulation(&N)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("mainWindow", "Open Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAHP.setText(QtGui.QApplication.translate("mainWindow", "AHP Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLingTbl.setText(QtGui.QApplication.translate("mainWindow", "Linguistic Table Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocGen.setText(QtGui.QApplication.translate("mainWindow", "Location Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("mainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("mainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearExistFeatcls.setText(QtGui.QApplication.translate("mainWindow", "Clear Exist Feature Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("mainWindow", "New Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDistMatGen.setText(QtGui.QApplication.translate("mainWindow", "Distance Matrix Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProxAnalyst.setText(QtGui.QApplication.translate("mainWindow", "Proximity Analyst", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("mainWindow", "Import Result to Feature Class", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSensViewer.setText(QtGui.QApplication.translate("mainWindow", "Sensitive Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClipFilter.setText(QtGui.QApplication.translate("mainWindow", "Clip Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowAltRank.setText(QtGui.QApplication.translate("mainWindow", "Show Alternatives Rank", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowAbsChg.setText(QtGui.QApplication.translate("mainWindow", "Show Absolute Change", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowRelChg.setText(QtGui.QApplication.translate("mainWindow", "Show Percent Change", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowSensList.setText(QtGui.QApplication.translate("mainWindow", "Sensitive List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowThVal.setText(QtGui.QApplication.translate("mainWindow", "Show Threshold Values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowCrtDegs.setText(QtGui.QApplication.translate("mainWindow", "Show Critically Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowSens.setText(QtGui.QApplication.translate("mainWindow", "Show Sensitivity Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConCrtTrees.setText(QtGui.QApplication.translate("mainWindow", "Hierarchical Network", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetLingVal.setText(QtGui.QApplication.translate("mainWindow", "Set Linguistic Values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBldRegPg.setText(QtGui.QApplication.translate("mainWindow", "Geographical Trisella", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompCrtProx.setText(QtGui.QApplication.translate("mainWindow", "Compute Criteria Proximity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAHPMatCon.setText(QtGui.QApplication.translate("mainWindow", "Satty Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSensAnalyst.setText(QtGui.QApplication.translate("mainWindow", "WSM Sensitive Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandom_Matrix.setText(QtGui.QApplication.translate("mainWindow", "Random Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoExp.setText(QtGui.QApplication.translate("mainWindow", "Auto Experience", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWPMSensAnalyst.setText(QtGui.QApplication.translate("mainWindow", "WPM Sensitive Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTreeRenderer.setText(QtGui.QApplication.translate("mainWindow", "Hierarchical Network Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenDistMat.setText(QtGui.QApplication.translate("mainWindow", "Generate Distance Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation.setText(QtGui.QApplication.translate("mainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

